### ISSUE TITLE
Good Progress

### ISSUE THREAD

**Issue by joehernandez11** [csoulakian/cs330s16p1#3]
Everything looks in order here. Nice and organized. It seems that you have some ideas and direction on where you want to take your code. Empty methods but you more or less know what you are going to code in those sections and what it's going to do. I'd like to come back and review this again once you have a bit more.

**Comment by csoulakian** [comment]
Thanks for the feedback! What empty methods are you referring to? In ReaderTest?

**Comment by joehernandez11** [comment]
Looks like you got it! Good work!

**Comment by csoulakian** [comment]
Thanks!
