### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by rgrover96** [csoulakian/cs330s16p1#4]
One thing I noticed was that you included a main class and there is nothing wrong with that, but try to work around that so that you don't need one. I'm only saying that because for this specific assignment, it said not to use a main class. But I know where you are coming from because I always include a main class when I code. This was the first time I didn't. Other than that, your code was very neat and organized and you had way more testing than actual coding, which was very good.

**Comment by csoulakian** [comment]
Thanks for the feedback! I thought the assignment said we didn't NEED a main method implying that it was optional, but now I see that it says that we will not have one. It was a lot easier for me to test the parser as I was coding by using the console to scan in sample tweets, but now that I have that down, I'll remove it. I already have all my test tweets coded and ready to go so I'll change the reader so it simply takes in a string message.

**Comment by csoulakian** [comment]
Fixed with [34f548a](https://github.com/csoulakian/cs330s16p1/commit/34f548a195fa3ab8079d968c37931fd9f7dc9707)

**Comment by csoulakian** [comment]
Fixed with [34f548a](https://github.com/csoulakian/cs330s16p1/commit/34f548a195fa3ab8079d968c37931fd9f7dc9707)
