### ISSUE TITLE
Good Work!

### ISSUE THREAD

**Issue by louiehernandez95** [csoulakian/cs330s16p1#7]
I like how you document all of your progress. And write the intention behind all of your classes and methods. I know you are not done with some of your methods ye but be proud of your work.

**Comment by csoulakian** [comment]
Thanks! I'm not sure if you have the latest commits, but it looks like I've already added all the methods.

**Comment by louiehernandez95** [comment]
Oh sorry I was looking at the wrong thing >_< awesome job!

**Comment by csoulakian** [comment]
It's cool, thanks for the feedback!
